### ISSUE TITLE
Where is 'vgg16-imagenet' model?

### ISSUE THREAD

**Issue by nsbb** [voxel51/platform-sdk#5]
When I tried some codes at `platform-sdk/eta/examples/demo_embed_vgg16`, I keep get same error messages.

> ModelError: No models found with base name 'vgg16-imagenet'

So I checked vgg16.py at my local `eta/core` folder.
line51 : `self.model = self.parse_string(d, "model", default="vgg16-imagenet")`

I changed 'vgg16-imagenet' as 'vgg16' but it still doesn't work.

It just gives me a message like below.
> ModelError: No models found with base name 'vgg16'

I searched every code that where is vgg16-imagenet model at my local `eta` folder.
But I couldn't find.

If you teach me what should I do, It will help me a lot.
Thank you. Regards.

**Comment by brimoor** [comment]
@nsbb It is not expected or necessary for you to run any tests from inside the `eta` submodule when installing the `platform-sdk`. The ETA library has two pieces:
(a) a core library of useful functions
(b) a data pipeline system for building and running ML pipelines

If you just want to use the `platform-sdk` to deploy your own custom analytics, you only need (a) from ETA. The tests that you were running from ETA are for (b). There is one extra ETA setup step that was missing from the `install.bash` script in `platform-sdk` in order to use (b) from ETA.

Although (b) is not necessary, I updated the install script in `platform-sdk` so that (b) will also work for you if desired.

Sorry for the confusion. This should be resolved by pulling the latest `develop` branch in `platform-sdk`:

```
cd platform-sdk
git checkout develop
git pull
git submodule update
```

**Comment by brimoor** [comment]
I verified that everything works on my machine in a fresh python virtual environment:

```
# Clone platform-sdk
git clone https://github.com/voxel51/platform-sdk
cd platform-sdk

# Install SDK
bash install.bash

# Run some examples to verify that ETA is working
cd eta
python examples/download_data.py
python examples/demo_images.py
eta run examples/demo_video/pipeline.json
#
# It is not necessary that the below commands (which run actual ML pipelines)
# work in order to use the platform SDK (which only requires some benign I/O
# capabilities from ETA); but we verify that they will work nonetheless
#
eta build -r examples/demo_video_formatter/request.json --run-now
python examples/demo_embed_vgg16/embed_image.py
```
